BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users" (
	"id_user"	INTEGER NOT NULL UNIQUE,
	"username"	TEXT NOT NULL UNIQUE,
	"icon"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Chats" (
	"id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL,
	"chat_participant"	BLOB NOT NULL,
	"icon"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "messages" (
	"id"	INTEGER NOT NULL,
	"id_user"	INTEGER NOT NULL,
	"id_chat"	INTEGER NOT NULL,
	"message"	TEXT NOT NULL
);
COMMIT;
