CREATE TABLE СhatParticipant (
	id	Int UNIQUE,
	chat_id	Int,
	user_id	Int
);
CREATE TABLE IF NOT EXISTS "Chat" (
	"id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL UNIQUE,
	"messages"	BLOB NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Session" (
	"id"	INTEGER NOT NULL UNIQUE,
	"id_user"	INTEGER NOT NULL UNIQUE,
	"key_session"	TEXT NOT NULL UNIQUE,
	FOREIGN KEY("id_user") REFERENCES "User"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "User" (
	"id"	INTEGER NOT NULL UNIQUE,
	"username"	TEXT NOT NULL UNIQUE,
	"email"	INTEGER NOT NULL UNIQUE,
	"password"	INTEGER NOT NULL UNIQUE,
	"icon"	TEXT NOT NULL,
	"key_sipher"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
