BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "СhatParticipant" (
	"id"	INTEGER UNIQUE,
	"chat_id"	INTEGER,
	"user_id"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("chat_id") REFERENCES "Users"
);
CREATE TABLE IF NOT EXISTS "Chat" (
	"id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL UNIQUE,
	"messages"	BLOB NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Session" (
	"id"	INTEGER NOT NULL UNIQUE,
	"id_user"	INTEGER NOT NULL UNIQUE,
	"key_session"	TEXT NOT NULL UNIQUE,
	FOREIGN KEY("id_user") REFERENCES "Users"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"username"	TEXT NOT NULL UNIQUE,
	"email"	INTEGER NOT NULL UNIQUE,
	"password"	INTEGER NOT NULL UNIQUE,
	"icon"	TEXT NOT NULL,
	"salt"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
